options_chapter_1 = {
    "options_0": {"A": "Take the pathway nonchalantly.",
                  "B": '"Ooooo. is that a bird?"',
                  "C": "Search around for a bit.",
                  "D": "Take the pathway carefully.",
                  },
    "options_1": {"A": "I'm just a wandering person, no reason to be frightened of me, "
                       "do you mind if I tag along?",
                  "B": "Action: *Gets on the ground and prostrates* 'Please take me to the nearby town!'",
                  "C": "No need to fear me. I just came from a tomb 2 hours this way, I don't know where to go.",
                  "D": "Action: *You run away in the opposite direction.*",
                  },
    "options_2": {"A": "Blacksmith",
                  "B": "General Goods Store",
                  "C": "Guild House",
                  "D": "The Inn",
                  },
    "options_3": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_4": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_5": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_6": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_7": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_8": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_9": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_10": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_11": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_12": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_13": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_14": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_15": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_16": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_17": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_18": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_19": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
    "options_20": {"A": "",
                  "B": "",
                  "C": "",
                  "D": "",
                  },
}
